# Schedule

This is a tentative schedule, **BUT** I will do my very best to stick to it, so that you may plan accordingly!

## Fall 2022  {-}				
				
				
Date | Topic | 				
|:-------|:------				
| 	Wednesday, August 24, 2022	| 	Fisker vs Tesla	| 
| 	Monday, August 29, 2022	| 	Robin Hood	| 
| 	Wednesday, August 31, 2022	| 	GM and FORD, Ch 1	| 
| 	Monday, September 5, 2022	| 	Quiz: Can you Say	| 
| 	Wednesday, September 7, 2022	| 	Quiz: CH 1 & 2	| 
| 	Monday, September 12, 2022	| 	Quiz: CH 3	| 
| 	Wednesday, September 14, 2022	| 	Quiz: CH 4	| 
| 	Monday, September 19, 2022	| 	Case and Review	| 
| 	Wednesday, September 21, 2022	| 	**EXAM 1**	| 
| 	Monday, September 26, 2022	| 	CH 5	| 
| 	Wednesday, September 28, 2022	| 	Case	| 
| 	Monday, October 3, 2022	| 	Quiz: CH 6	| 
| 	Wednesday, October 5, 2022	| 	Aldi & Walmart	| 
| 	Monday, October 10, 2022	| 	FALL BREAK	| 
| 	Wednesday, October 12, 2022	| 	Quiz: CH 7	| 
| 	Monday, October 17, 2022	| 	Groups & Companies	| 
| 	Wednesday, October 19, 2022	| 	Project Rubric	| 
| 	Monday, October 24, 2022	| 	Quiz: Ch. 8	| 
| 	Wednesday, October 26, 2022	| 	Quiz: Ch. 9	| 
| 	Monday, October 31, 2022	| 	Groups & Companies	| 
| 	Wednesday, November 2, 2022	| 	Case and Review	| 
| 	Monday, November 7, 2022	| 	**EXAM 2**	| 
| 	Wednesday, November 9, 2022	| 	Rough Draft Due 20%	| 
| 	Monday, November 14, 2022	| 	GROUP MEETINGS	| 
| 	Wednesday, November 16, 2022	| 	GROUP MEETINGS	| 
| 	Monday, November 21, 2022	| 	Final Draft Due 80%	| 
| 	Wednesday, November 23, 2022	| 	THANKSGIVING BREAK	| 
|	  Monday, November 28, 2022	| 	**PRESENTATIONS**	| 
| 	Wednesday, November 30, 2022	| 	**PRESENTATIONS**	| 
|	 Monday, December 5, 2022	| 	LAST DAY OF CLASS	| 

## Spring 2022  {-}

Date | Topic | 				
|:-------|:------			
| 	Date	| 	A1	| 
| 	Monday, January 10, 2022	| 	R basics and install	| 
| 	Wednesday, January 12, 2022	| 	R basics and workflows	| 
| 	Friday, January 14, 2022	| 	QUIZ 1 	| 
| 	Monday, January 17, 2022	| 	MLK Holiday	| 
| 	Wednesday, January 19, 2022	| 	Objects and Arithmetic	| 
| 	Friday, January 21, 2022	| 	QUIZ	| 
| 	Monday, January 24, 2022	| Summaries and Subscripting	| 
| 	Wednesday, January 26, 2022	| 	Matrices and `mtcars`	| 
| 	Friday, January 28, 2022	| 	QUIZ	| 
| 	Monday, January 31, 2022	| 	Class	| 
| 	Wednesday, February 2, 2022	| 	Class	| 
| 	Friday, February 4, 2022	| 	QUIZ	| 
| 	Monday, February 7, 2022	| 	Social Dilemma and Review	| 
| 	Wednesday, February 9, 2022	| 	**EXAM 1**	| 
| 	Friday, February 11, 2022	| 	Class	| 
| 	Monday, February 14, 2022	| 	Class	| 
| 	Wednesday, February 16, 2022	| 	Online Class	| 
| 	Friday, February 18, 2022	| 	Online QUIZ	| 
| 	Monday, February 21, 2022	| 	Class	| 
| 	Wednesday, February 23, 2022	| 	Class	| 
| 	Friday, February 25, 2022	| 	QUIZ	| 
| 	Monday, February 28, 2022	| 	Class	| 
| 	Wednesday, March 2, 2022	| 	Class	| 
| 	Friday, March 4, 2022	| 	QUIZ	| 
| 	Monday, March 7, 2022	| 	**EXAM 2**	| 
| 	Wednesday, March 9, 2022	| 	Online Class	| 
| 	Friday, March 11, 2022	| 	Online Class	| 
| 	Monday, March 14, 2022	| 	SPRING BREAK	| 
| 	Wednesday, March 16, 2022	| 	SPRING BREAK	| 
| 	Friday, March 18, 2022	| 	SPRING BREAK	| 
| 	Monday, March 21, 2022	| 	Class	| 
| 	Wednesday, March 23, 2022	| 	Class	| 
| 	Friday, March 25, 2022	| 	QUIZ	| 
| 	Monday, March 28, 2022	| 	ADVISING WEEK	| 
| 	Wednesday, March 30, 2022	| 	ADVISING WEEK	| 
| 	Friday, April 1, 2022	| 	QUIZ	| 
| 	Monday, April 4, 2022	| 	Class	| 
| 	Wednesday, April 6, 2022	| 	Class	| 
| 	Friday, April 8, 2022	| 	QUIZ	| 
| 	Monday, April 11, 2022	| 	Class	| 
| 	Wednesday, April 13, 2022	| 	**EXAM 3**	| 
| 	Friday, April 15, 2022	| 	Easter Holidays	| 
| 	Monday, April 18, 2022	| 	Easter Holidays	| 
| 	Wednesday, April 20, 2022	| 	Class	| 
| 	Friday, April 22, 2022	| 	QUIZ	| 
| 	Monday, April 25, 2022	| 	Class	| 
| 	Wednesday, April 27, 2022	| 	QUIZ	| 
| 	Friday, April 29, 2022	| 	LAST DAY	| 
| 	Monday, May 2, 2022	| 	**Final Exam** 5:30 p.m. – E period	| 

